version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/taste-it
    ports:
      - 3010:3000
    image: app:taste-it
    container_name: tasteit_container
    command: npm start
